behaviors:
  WhereToStack:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 2048
      learning_rate: 5.0e-4
      beta: 1.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 32
    summary_freq: 200
    threaded: false
environment_parameters:
  dim:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: WhereToStack
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.08
        value: 2.0
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: WhereToStack
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
        value: 3.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: WhereToStack
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.5
        value: 4.0
      - name: Lesson3
        value: 5.0
      