behaviors:
  WhereToStack:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 3
    behavioral_cloning:
      demo_path: 'H:/programming/unity/ml-agents-release_17/results/Demos'
      strength: 1
      steps: 50000
      batch_size: 512
      num_epoch: 3
      samples_per_update: 0
    reward_signals:
      #extrinsic:
      #  strength: 0.2
      #  gamma: 0.99
      gail:
        gamma: 0.99
        strength: 1
        demo_path: 'H:/programming/unity/ml-agents-release_17/results/Demos'
    max_steps: 500000
    time_horizon: 32
    summary_freq: 200
    threaded: false
       
    